using LenovoSmartFix.Core.Models;
using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;

namespace LenovoSmartFix.Service.Escalation;

/// <summary>
/// QuestPDF document definition for the human-readable escalation summary.
/// </summary>
public sealed class SmartFixPdfDocument : IDocument
{
    private readonly EscalationPacket _packet;

    // Lenovo Red
    private static readonly string LenovoRed = "#E1140A";

    public SmartFixPdfDocument(EscalationPacket packet) => _packet = packet;

    public DocumentMetadata GetMetadata() => DocumentMetadata.Default with
    {
        Title = $"Lenovo SmartFix — Support Summary",
        Author = "LenovoSmartFix",
        CreationDate = _packet.ExportedAt.DateTime
    };

    public DocumentSettings GetSettings() => DocumentSettings.Default;

    public void Compose(IDocumentContainer container)
    {
        container.Page(page =>
        {
            page.Size(PageSizes.A4);
            page.Margin(30);
            page.DefaultTextStyle(t => t.FontFamily("Segoe UI").FontSize(10));

            page.Header().Element(ComposeHeader);
            page.Content().Element(ComposeContent);
            page.Footer().AlignCenter().Text(t =>
            {
                t.Span("Generated by Lenovo SmartFix  ·  ").FontSize(8).FontColor(Colors.Grey.Medium);
                t.Span(_packet.ExportedAt.ToString("yyyy-MM-dd HH:mm UTC")).FontSize(8).FontColor(Colors.Grey.Medium);
            });
        });
    }

    private void ComposeHeader(IContainer c)
    {
        c.Column(col =>
        {
            col.Item().Row(row =>
            {
                row.RelativeItem().Column(inner =>
                {
                    inner.Item()
                         .Text("Lenovo SmartFix")
                         .FontSize(20).Bold().FontColor(LenovoRed);
                    inner.Item()
                         .Text("Support-Ready Summary")
                         .FontSize(12).FontColor(Colors.Grey.Darken2);
                });
                row.ConstantItem(100).AlignRight().AlignMiddle()
                   .Text($"ID: {_packet.PacketId[..8]}")
                   .FontSize(8).FontColor(Colors.Grey.Medium);
            });

            col.Item().PaddingVertical(4)
               .LineHorizontal(2).LineColor(LenovoRed);
        });
    }

    private void ComposeContent(IContainer c)
    {
        c.Column(col =>
        {
            col.Spacing(12);

            // Symptom
            col.Item().Element(SectionHeader("Reported Issue"));
            col.Item().Text(_packet.PrimarySymptom).SemiBold();

            // Device
            col.Item().Element(SectionHeader("Device"));
            col.Item().Element(DeviceTable());

            // Diagnosis
            col.Item().Element(SectionHeader("Diagnosis"));
            col.Item().Element(DiagnosisCard());

            // Health highlights
            col.Item().Element(SectionHeader("Health Snapshot"));
            col.Item().Element(HealthTable());

            // Update status
            col.Item().Element(SectionHeader("Update Status"));
            col.Item().Element(UpdateTable());

            // Actions attempted
            if (_packet.ActionsAttempted.Any())
            {
                col.Item().Element(SectionHeader("Actions Attempted"));
                col.Item().Element(ActionsTable());
            }

            // Outcome
            col.Item().Element(SectionHeader("Outcome"));
            col.Item().Background(Colors.Grey.Lighten3).Padding(8)
               .Text(_packet.Outcome).SemiBold();

            if (!string.IsNullOrEmpty(_packet.UnresolvedReason))
                col.Item().Text($"Unresolved reason: {_packet.UnresolvedReason}")
                   .FontColor(Colors.Red.Darken1);
        });
    }

    private static Action<IContainer> SectionHeader(string title) =>
        c => c.BorderBottom(1).BorderColor(Colors.Grey.Lighten2).PaddingBottom(2)
              .Text(title).FontSize(11).Bold();

    private Action<IContainer> DeviceTable() => c =>
    {
        var d = _packet.DeviceProfile;
        c.Table(t =>
        {
            t.ColumnsDefinition(cd => { cd.RelativeColumn(); cd.RelativeColumn(2); });
            Row(t, "Model", d.Model);
            Row(t, "OS", $"{d.OsVersion} (Build {d.OsBuild})");
            Row(t, "BIOS", d.BiosVersion);
            Row(t, "Lenovo Utilities", string.Join(", ", d.InstalledLenovoUtilities.Keys));
        });
    };

    private Action<IContainer> DiagnosisCard() => c =>
    {
        var dec = _packet.DiagnosisDecision;
        var bg = dec.Path switch
        {
            DiagnosisPath.AutoResolve => Colors.Green.Lighten4,
            DiagnosisPath.GuidedResolution => Colors.Orange.Lighten4,
            DiagnosisPath.Escalate => Colors.Red.Lighten4,
            _ => Colors.Grey.Lighten4
        };

        c.Background(bg).Padding(8).Column(col =>
        {
            col.Item().Text($"Path: {dec.Path}  ·  Confidence: {dec.Confidence:P0}  ·  Risk: {dec.RiskLevel}")
               .SemiBold();
            col.Item().Text(dec.UserFacingReason);
            if (dec.EvidenceItems.Any())
            {
                col.Item().PaddingTop(4).Text("Evidence:").FontSize(9).Italic();
                foreach (var e in dec.EvidenceItems)
                    col.Item().Text($"• {e}").FontSize(9);
            }
        });
    };

    private Action<IContainer> HealthTable() => c =>
    {
        var h = _packet.HealthSnapshot;
        c.Table(t =>
        {
            t.ColumnsDefinition(cd => { cd.RelativeColumn(); cd.RelativeColumn(2); });
            Row(t, "Battery Health", $"{h.BatteryHealthPercent}%");
            Row(t, "Disk Used", $"{h.DiskUsedPercent:F1}%");
            Row(t, "RAM Used", $"{h.RamUsedPercent:F1}%");
            Row(t, "CPU Load", $"{h.CpuLoadPercent:F0}%");
            Row(t, "Wi-Fi Reconnects (24h)", h.WifiReconnectsLast24h.ToString());
            Row(t, "App Crashes (7d)", h.AppCrashesLast7Days.ToString());
            Row(t, "System Crashes (7d)", h.SystemCrashesLast7Days.ToString());
        });
    };

    private Action<IContainer> UpdateTable() => c =>
    {
        var u = _packet.UpdateStatus;
        c.Table(t =>
        {
            t.ColumnsDefinition(cd => { cd.RelativeColumn(2); cd.RelativeColumn(); cd.RelativeColumn(); });
            t.Header(h =>
            {
                h.Cell().Text("Component").SemiBold();
                h.Cell().Text("Current").SemiBold();
                h.Cell().Text("State").SemiBold();
            });
            HeaderRow(t, "BIOS", u.Bios.CurrentVersion, u.Bios.State.ToString());
            foreach (var d in u.Drivers.Where(d => d.IsCritical))
                HeaderRow(t, d.ComponentName, d.CurrentVersion, d.State.ToString());
        });
    };

    private Action<IContainer> ActionsTable() => c =>
    {
        c.Table(t =>
        {
            t.ColumnsDefinition(cd =>
            {
                cd.RelativeColumn(2);
                cd.RelativeColumn();
                cd.RelativeColumn(2);
            });
            t.Header(h =>
            {
                h.Cell().Text("Action").SemiBold();
                h.Cell().Text("Result").SemiBold();
                h.Cell().Text("Detail").SemiBold();
            });
            foreach (var a in _packet.ActionsAttempted)
                HeaderRow(t, a.ActionName, a.Result.ToString(), a.ResultDetail ?? string.Empty);
        });
    };

    private static void Row(TableDescriptor t, string label, string value)
    {
        t.Cell().Padding(2).Text(label).FontColor(Colors.Grey.Darken2);
        t.Cell().Padding(2).Text(value);
    }

    private static void HeaderRow(TableDescriptor t, string c1, string c2, string c3)
    {
        t.Cell().Padding(2).Text(c1);
        t.Cell().Padding(2).Text(c2);
        t.Cell().Padding(2).Text(c3);
    }
}
